//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEvents.Core.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportEventsDBEntities : DbContext
    {
        public SportEventsDBEntities()
            : base("name=SportEventsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Događaj> Događaj { get; set; }
        public virtual DbSet<DogađajNatjecatelj> DogađajNatjecatelj { get; set; }
        public virtual DbSet<Grad> Gradovi { get; set; }
        public virtual DbSet<Mjesto> Mjesta { get; set; }
        public virtual DbSet<Natjecatelj> Natjecatelji { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
    }
}
