//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEvents.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DogađajNatjecatelj
    {
        [Key]
        public int pk_događaj_natjecatelj { get; set; }
        public int fk_događaj { get; set; }
        public int fk_natjecatelj { get; set; }
    
        public virtual Događaj Događaj { get; set; }
        public virtual Natjecatelj Natjecatelj { get; set; }
    }
}
