//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEvents.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Događaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Događaj()
        {
            this.DogađajNatjecatelj = new HashSet<DogađajNatjecatelj>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        [Key]
        public int pk_događaj { get; set; }
        public int fk_sport { get; set; }
        public int fk_mjesto { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<int> broj_posjetitelja { get; set; }
    
        public virtual Mjesto Mjesto { get; set; }
        public virtual Sport Sport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogađajNatjecatelj> DogađajNatjecatelj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
